# Generated by Django 4.2.11 on 2024-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='blogs-images/default.jpg', upload_to='blogs-images/'),
        ),
    ]
